swagger: '2.0'
info:
  description: API definition DebugChain project
  version: 1.0.0
  title: DebugChain
host: '???'
basePath: /api
schemes:
  - http
paths:
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        default:
          description: successful operation
  
  '/user/{username}':
    get:
      tags:
        - user
      summary: Get user by user name
      description: ''
      operationId: getUserByName
      produces:
        - application/xml
        - application/json
      parameters:
        - name: username
          in: path
          description: 'The name that needs to be fetched. Use user1 for testing. '
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    put:
      tags:
        - user
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      produces:
        - application/xml
        - application/json
      parameters:
        - name: username
          in: path
          description: name that need to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Updated user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '400':
          description: Invalid user supplied
        '404':
          description: User not found
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      produces:
        - application/xml
        - application/json
      parameters:
        - name: username
          in: path
          description: The name that needs to be deleted
          required: true
          type: string
      responses:
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
  /issue:
    get:
      tags:
        - issue
  /project:
    get:
      tags:
        - project
definitions:
  Issue:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: ID from GitLab
      projectId:
        type: integer
        format: int64
        description: ID from GitLab
      webUrl:
        type: string
        description: GitLab link
      title:
        type: string
      description:
        type: string
      state:
        type: string
        description: GitLab Status
        enum:
          - opened
          - closed
      approve:
        type: boolean
        default: false
      lockedAdress:
        type: string
        description: locked by user with pub-key
      lockedGitLabId:
        type: integer
        format: int64
        description: locked by user with GitLab ID
      complete:
        type: boolean
        default: false
    xml:
      name: Issue
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      email:
        type: string
      token:
        type: string
      adress:
        type: string
        description: ETH pub-key
    xml:
      name: User
  Project:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      description:
        type: string
      visibility:
        type: string
        description: GitLab Status
        enum:
          - public
          - internal
          - private
      maintainer:
        type: integer
        format: int64
      webUrl:
        type: string
      issuesEnabled:
        type: boolean
    xml:
      name: Project
  ProjectReviewer:
    type: object
    properties:
      id:
        type: integer
        format: int64
      projectId:
        type: integer
        format: int64
      userId:
        type: integer
        format: int64
    xml:
      name: ProjectReviewer
  IssueReviewer:
    type: object
    properties:
      id:
        type: integer
        format: int64
      issueId:
        type: integer
        format: int64
      userId:
        type: integer
        format: int64
      state:
        type: string
        description: GitLab Status
        enum:
          - confirmed
          - rejected
          - sentback
    xml:
      name: IssueReviewer
