web3j.client-address: "http://localhost:9545"
server:
    port: 8081
    restPath: /api
spring:
    jpa:
        databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
        hibernate:
            ddlAuto: none