web3j.client-address: "http://localhost:9545"
server:
    port: 8080
    restPath: /api
spring:
    jpa:
        databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
        hibernate:
            ddlAuto: none
    cache:
      jcache:
        config: classpath:ehcache.xml