web3j.client-address: "http://debugchain.k202.de:9545"
server:
    port: 8080
    restPath: /api
spring:
    jpa:
        databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
        hibernate:
            ddlAuto: none
    cache:
      jcache:
        config: classpath:ehcache.xml
oauth2:
    gitlab:
        userEndpoint: http://debugchain.k202.de/api/v4/user